// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"github.com/topfreegames/pitaya/v2"
	"hang-king-game/app/batt/internal/biz"
	"hang-king-game/app/batt/internal/conf"
	"hang-king-game/app/batt/internal/data"
	"hang-king-game/app/batt/internal/server"
	"hang-king-game/app/batt/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (pitaya.Pitaya, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	app := server.NewServer(confServer.Websocket,logger)
	components :=server.WsComponents(greeterService)
	buildWsApp(app,components)
	return app, func() {
		cleanup()
	}, nil
}
